apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hewb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-hewb@sha256:7b24fd7db8b19e72dd4a098ece705c77e6beb1cea8208cf3bc9a543492b2325d
        name: my-nodejs
        resources: {}
status: {}
